# Uncomment the following lines to enable the Corne RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

CONFIG_ZMK_POINTING=y

# Uncomment the following line to enable the Corne OLED Display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# Power management
# Milliseconds of inactivity before entering idle state (10 minutes)
CONFIG_ZMK_IDLE_TIMEOUT=600000
# Enable deep sleep support
CONFIG_ZMK_SLEEP=y
# Milliseconds of inactivity before entering deep sleep (15 minutes)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# CONFIG_NICE_VIEW_GEM_ANIMATION_MS=9600