# Uncomment the following lines to enable the Corne RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

CONFIG_ZMK_POINTING=y

# Power management
# Milliseconds of inactivity before entering idle state (5 minutes)
CONFIG_ZMK_IDLE_TIMEOUT=300000
# Enable deep sleep support
CONFIG_ZMK_SLEEP=y
# Milliseconds of inactivity before entering deep sleep (15 minutes)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=600000

CONFIG_NICE_VIEW_GEM_ANIMATION_MS=4800

# Display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
# Enable a widget to show words per minute
#CONFIG_ZMK_WIDGET_WPM_STATUS=n
#CONFIG_ZMK_WIDGET_LAYER_STATUS=n
#CONFIG_ZMK_WIDGET_PERIPHERAL_STATUS=n
#Bongo cat猫猫敲键盘动画
#CONFIG_ZMK_WIDGET_BONGO_CAT=y
#CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# Increase the bluetooth transmission power
# CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
# CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y

# enable eager debouncing (reduce input lag)
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5